name: Develop Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 21
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false
      - name: checkout
        uses: actions/checkout@v4
      - name: fix permissions
        run: chmod +x gradlew

      - name: run build and test
        run: ./gradlew build

